version: '3.4'

services:
  catalogdb:
    image: postgres
  
  basketdb:
    image: postgres  
    
  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  catalog_api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog_API/Dockerfile

  bakset_api:
    image: ${DOCKER_REGISTRY-}baksetapi
    build:
      context: .
      dockerfile: Services/Basket/Bakset_API/Dockerfile

  discount_grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount_Grpc/Dockerfile

  ordering_api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering_API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:





